# Generated by Django 6.1.1 on 2026-09-14 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=150)),
                ('role_associe', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.CharField(blank=True, max_length=150)),
                ('statut_activite', models.CharField(choices=[('actif', 'Actif'), ('obsolete', 'Obsolète')], default='actif', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type_document', models.CharField(choices=[('site_web', 'Site web'), ('powerpoint', 'PowerPoint'), ('pdf', 'PDF'), ('reglement_interieur', 'Règlement intérieur'), ('guide_etudiant', 'Guide étudiant'), ('procedure', 'Procédure'), ('calendrier', 'Calendrier'), ('faq', 'FAQ'), ('annonce', 'Annonce'), ('autre', 'Autre')], max_length=30)),
                ('fichier_original', models.CharField(blank=True, help_text='Chemin du fichier ou URL de la source', max_length=500)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('mixte', 'Mixte')], default='fr', max_length=10)),
                ('categorie_principale', models.CharField(choices=[('ecole', 'École'), ('specialites', 'Spécialités'), ('admission', 'Admission'), ('inscription', 'Inscription'), ('etudes', 'Études'), ('examens', 'Examens'), ('reglement', 'Règlement'), ('stages', 'Stages'), ('services_etudiants', 'Services étudiants'), ('actualites', 'Actualités'), ('faq', 'FAQ'), ('contacts', 'Contacts')], max_length=30)),
                ('date_creation_document', models.DateField(blank=True, help_text="Date du document lui-même (pas de l'import)", null=True)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_verification', models.DateField(blank=True, help_text="Dernière fois qu'un humain a confirmé la validité de ce document", null=True)),
                ('statut_officialite', models.CharField(choices=[('officiel_valide', 'Officiel validé'), ('officiel_non_valide', 'Officiel non validé'), ('interne', 'Interne'), ('public_informel', 'Public informel')], max_length=30)),
                ('niveau_confiance', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], max_length=10)),
                ('statut_activite', models.CharField(choices=[('actif', 'Actif'), ('obsolete', 'Obsolète'), ('brouillon', 'Brouillon'), ('archive', 'Archivé')], default='brouillon', max_length=15)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('notes_internes', models.TextField(blank=True, help_text='Commentaires internes — jamais exposés au chatbot')),
                ('remplace_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_par', to='knowledge.document')),
            ],
            options={
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu_texte', models.TextField()),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], max_length=5)),
                ('categorie', models.CharField(choices=[('ecole', 'École'), ('specialites', 'Spécialités'), ('admission', 'Admission'), ('inscription', 'Inscription'), ('etudes', 'Études'), ('examens', 'Examens'), ('reglement', 'Règlement'), ('stages', 'Stages'), ('services_etudiants', 'Services étudiants'), ('actualites', 'Actualités'), ('faq', 'FAQ'), ('contacts', 'Contacts')], max_length=30)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('ordre_dans_document', models.PositiveIntegerField(default=0)),
                ('statut_activite', models.CharField(choices=[('en_attente_validation', 'En attente de validation'), ('actif', 'Actif'), ('obsolete', 'Obsolète'), ('desactive_manuellement', 'Désactivé manuellement')], default='en_attente_validation', max_length=25)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document_id', 'ordre_dans_document'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe')], max_length=5)),
                ('categorie', models.CharField(choices=[('ecole', 'École'), ('specialites', 'Spécialités'), ('admission', 'Admission'), ('inscription', 'Inscription'), ('etudes', 'Études'), ('examens', 'Examens'), ('reglement', 'Règlement'), ('stages', 'Stages'), ('services_etudiants', 'Services étudiants'), ('actualites', 'Actualités'), ('faq', 'FAQ'), ('contacts', 'Contacts')], max_length=30)),
                ('statut_activite', models.CharField(choices=[('actif', 'Actif'), ('obsolete', 'Obsolète')], default='actif', max_length=15)),
                ('date_derniere_maj', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='knowledge.document')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
