# Generated by Django 6.1.1 on 2026-09-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('site_web', 'Site web'), ('powerpoint', 'PowerPoint'), ('pdf', 'PDF'), ('reglement_interieur', 'Règlement intérieur'), ('guide_etudiant', 'Guide étudiant'), ('programme_filiere', 'Programme de filière'), ('procedure', 'Procédure'), ('calendrier', 'Calendrier'), ('faq', 'FAQ'), ('annonce', 'Annonce'), ('autre', 'Autre')], max_length=30),
        ),
    ]
