# Generated by Django 6.1.1 on 2026-09-14 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('api_test', 'Test API')], default='api_test', max_length=20)),
                ('langue_detectee', models.CharField(blank=True, max_length=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_activite', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=10)),
                ('contenu', models.TextField()),
                ('sources_utilisees', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSansReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_utilisateur', models.TextField()),
                ('langue', models.CharField(blank=True, max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('raison', models.CharField(choices=[('aucune_info_trouvee', 'Aucune information trouvée'), ('contradiction_detectee', 'Contradiction détectée'), ('hors_perimetre', 'Hors périmètre'), ('erreur_technique', 'Erreur technique')], max_length=30)),
                ('traitee', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_sans_reponse', to='chat.conversation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
